type WithdrawalPhase =
  | 'PROPOSING_ON_CHAIN'
  | 'PROVE'
  | 'PROVE_TX_PENDING'
  | 'PROVE_TX_FAILURE'
  | 'CHALLENGE_WINDOW'
  | 'FINALIZE'
  | 'FINALIZE_TX_PENDING'
  | 'FINALIZE_TX_FAILURE'
  | 'FUNDS_WITHDRAWN';

type DepositPhase = 'DEPOSIT_TX_PENDING' | 'FUNDS_DEPOSITED' | 'DEPOSIT_TX_FAILURE';

type CCTPBridgePhase =
  | 'INITIATE_CCTP_BRIDGE_PENDING'
  | 'INITIATE_CCTP_BRIDGE_FAILED'
  | 'FINALIZE_CCTP_BRIDGE'
  | 'FINALIZE_CCTP_BRIDGE_PENDING'
  | 'FINALIZE_CCTP_BRIDGE_FAILED'
  | 'CCTP_BRIDGE_COMPLETE';

export type { DepositPhase, WithdrawalPhase, CCTPBridgePhase };
