services:
  web:
    containers:
      web:
        resources:
          limits:
            memory: 500M
          requests:
            cpu: 50m
            memory: 500M
        image: protocols/base-web/goerli-bridge
    target_group_bindings:
      web: web-goerli-bridge-protocols--k8s
    scaling:
      min: 1
      max: 1
      targetcpu: 80