_shared_step: &shared_step
  commands:
    - tools/ci/setup.sh
  plugins:
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:current
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - 'BUILDKITE_API_TOKEN'
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
  agents:
    queue: docker
    resource_class: large
  retry:
    automatic:
      limit: 1
  env:
    NODE_OPTIONS: --max-old-space-size=8192

steps:
  - label: Build
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn build

  - label: Lint
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn lint
