services:
  web:
    containers:
      web:
        resources:
          limits:
            memory: 500M
          requests:
            cpu: 50m
            memory: 500M
        image: protocols/base-web/docs
    target_group_bindings:
      web: web-docs-protocols-base-web-k8s
    scaling:
      min: 3
      max: 10
      targetcpu: 80
shared_env:
  APP_STAGE: "production"
  AUTH_ENABLED: "false"
  BASIC_AUTH_CREDENTIALS: "testnet:MQBMPeIaLq1vuhB9UGsNRw private:amqmDE7O8r6YAxPsJvQp4hWmSsEItJJ2YkmdTdGjkU"
