services:
  web:
    containers:
      web:
        resources:
          limits:
            memory: 3G
          requests:
            cpu: 50m
            memory: 1G
        image: protocols/base-web/docs
    target_group_bindings:
      web: web-docs-protocols-base-web-k8s
    scaling:
      min: 3
      max: 10
      targetcpu: 80
shared_env:
  APP_STAGE: "production"
  AUTH_ENABLED: "false"
secret_env:
  BASIC_AUTH_CREDENTIALS: config_service_secret://protocols/base-web-docs|basic_auth_credentials