name: Docs request
description: Request new docs, or changes to existing docs
title: 'Docs Request: '
labels: ['type: docs']

body:
  - type: textarea
    id: problem
    attributes:
      label: What is the issue you are encountering with the docs?
      description: A clear and concise description of what is wrong, missing, or unclear.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links to Impacted Docs
      description: Please paste links to specific pages on docs.base.org that are related to your request.

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like to see.
      description: A clear and concise description of what you want to see in the docs.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the concern can be added here.
